squat:
  comparison_features: 
    - left_knee
    - right_knee
    - left_hip
    - right_hip

  mistakes_table:
      fix_info: "Go lower!"
      errors: 
        - angle_name: right_knee_pitch
          threshold: 15
        - angle_name: left_knee_pitch
          threshold: 15
        - angle_name: right_hip_pitch
          threshold: 15
        - angle_name: left_hip_pitch
          threshold: 15

    feet_too_wide:
      fix_info: "Keep your legs wider!"
      errors: 
        - angle_name: right_knee_pitch
          threshold: 15
        - angle_name: left_knee_pitch
          threshold: 15
        - angle_name: right_hip_pitch
          threshold: 15
        - angle_name: left_hip_pitch
          threshold: 15
