mediapipe:
  joints:
    11: left shoulder
    12: right shoulder
    13: left elbow
    14: right elbow
    15: left wrist
    16: right wrist
    23: left hip
    24: right hip
    25: left knee
    26: right knee
    27: left ankle
    28: right ankle
    29: left heel
    30: right heel
    31: left foot index
    32: right foot index

  connections:
    head:
      - [0, 1]
      - [1, 2]
      - [2, 3]
      - [3, 7]
      - [0, 4]
      - [4, 5]
      - [5, 6]
      - [6, 8]
      - [10, 9]

    torso:
      - [11, 12]
      - [11, 13]
      - [13, 15]
      - [15, 17]
      - [17, 19]
      - [19, 21]
      - [12, 14]
      - [14, 16]
      - [16, 18]
      - [18, 20]
      - [20, 16]
      - [16, 22]
      - [12, 24]
      - [24, 23]
      - [11, 23]
      - [24, 26]
      - [26, 28]
      - [28, 30]
      - [30, 32]
      - [32, 28]
      - [23, 25]
      - [25, 27]
      - [27, 29]
      - [29, 31]
      - [31, 27]

  angles: 
    left_knee: [27, 25, 23]
    right_knee: [28, 26, 24]
    left_elbow: [11, 13, 15]
    right_elbow: [12, 14, 16]
    left_shoulder: [13, 11, 12]
    right_shoulder: [11, 12, 14]
    left_hip: [11, 23, 25]
    right_hip: [12, 24, 26]

openpose:
  joints:
    0: nose
    1: upper spine
    2: right shoulder
    3: right elbow
    4: right hand
    5: left shoulder
    6: left elbow
    7: left hand
    8: lower spine
    9: right hip
    10: right knee
    11: right foot
    12: left hip
    13: left knee
    14: left foot
  
  connections:
    head:
      - [0, 15]
      - [0, 16]
      - [16, 18]
      - [15, 17]

    torso:
      - [1, 2]
      - [2, 3]
      - [3, 4]
      - [1, 5]
      - [5, 6]
      - [6, 7]
      - [1, 8]
      - [8, 9]
      - [9, 10]
      - [10, 11]
      - [8, 9]
      - [9, 10]
      - [10, 11]
      - [8, 12]
      - [12, 13]
      - [13, 14]

  angles:
    left_knee: [12, 13, 14]
    right_knee: [9, 10, 11]
    left_elbow: [5, 6, 7]
    right_elbow: [2, 3, 4]
    left_shoulder: [2, 5, 6]
    right_shoulder: [5, 2, 3]
    left_hip: [5, 12, 13]
    right_hip: [2, 9, 10]
